---
title: Inference and effect size
output:
  xaringan::moon_reader:
    css: "lab-slides.css"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
editor_options: 
  chunk_output_type: console
---

### Reminders

.large[
* Exam 1 next Friday (10/10)
  * Review day next Wednesday (10/8)
* Exam 1 material: everything through the end of this week (10/3)
  * I will not make you write any R code
  * You will need to read and interpret R output
  * Bring a scientific calculator! Phones are not allowed.
* Studying tips:
  * Practice questions on the course website
  * Look back at class activities
  * Go over homework questions
]

---

### Last time: Activity

.large[
```
             Estimate Std. Error z value Pr(>|z|)    
(Intercept) -2.507329   0.311939  -8.038 9.14e-16 ***
loss        -0.846499   0.238335  -3.552 0.000383 ***
smoke100    -0.137151   0.035816  -3.829 0.000128 ***
hlthplan     0.613613   0.051233  11.977  < 2e-16 ***
age         -0.012148   0.001043 -11.652  < 2e-16 ***
height       0.056845   0.004520  12.577  < 2e-16 ***
```

The standard deviation of the `loss` variable is 0.074.

.question[
How do the odds of exercise change with a one standard deviation increase in loss, holding the other variables constant?
]
]

---

### Activity

.large[
```
             Estimate Std. Error z value Pr(>|z|)    
(Intercept) -2.507329   0.311939  -8.038 9.14e-16 ***
loss        -0.846499   0.238335  -3.552 0.000383 ***
...          ...        ...        ...    ...
```

The standard deviation of the `loss` variable is 0.074.

.question[
Want to test whether a one-standard deviation increase in `loss` is associated with a decrease in the odds of at least 5% (holding other variables constant).
]
]

---

### Statistical "significance" vs. practical significance

.large[
* A small p-value in the test of $H_0: \beta = 0$ is evidence against $H_0$
* However, we could have $\beta \neq 0$ but still *very close* to 0
* Small p-values therefore do not mean an effect has *practical* significance
* It is common for domain experts to specify what effect size would be of practical significance, and then we can test whether the effect is at least that big
]

---

### Activity

.large[
Work on the class activity (handout), then we will discuss as a group.
]

---

### Activity

.large[
```
Coefficients:
               Estimate Std. Error z value Pr(>|z|)    
(Intercept)   -3.989979   1.139951  -3.500 0.000465 ***
gre            0.002264   0.001094   2.070 0.038465 *  
gpa            0.804038   0.331819   2.423 0.015388 *  
factor(rank)2 -0.675443   0.316490  -2.134 0.032829 *  
factor(rank)3 -1.340204   0.345306  -3.881 0.000104 ***
factor(rank)4 -1.551464   0.417832  -3.713 0.000205 ***
```

.question[
Given your friend's GPA (3.95), school (rank 3), and current GRE score (590), what is your estimated probability that they will be accepted to graduate school?
]
]

---

### Activity

.large[
```
Coefficients:
               Estimate Std. Error z value Pr(>|z|)    
(Intercept)   -3.989979   1.139951  -3.500 0.000465 ***
gre            0.002264   0.001094   2.070 0.038465 *  
gpa            0.804038   0.331819   2.423 0.015388 *  
factor(rank)2 -0.675443   0.316490  -2.134 0.032829 *  
factor(rank)3 -1.340204   0.345306  -3.881 0.000104 ***
factor(rank)4 -1.551464   0.417832  -3.713 0.000205 ***
```

.question[
The standard deviation of GRE scores is 115.5 points. If your friend re-took the GRE and increased their score by one standard deviation, what would be the estimated change in their *odds* of being accepted?
]
]

---

### Activity

.large[
```
Coefficients:
               Estimate Std. Error z value Pr(>|z|)    
(Intercept)   -3.989979   1.139951  -3.500 0.000465 ***
gre            0.002264   0.001094   2.070 0.038465 *  
gpa            0.804038   0.331819   2.423 0.015388 *  
factor(rank)2 -0.675443   0.316490  -2.134 0.032829 *  
factor(rank)3 -1.340204   0.345306  -3.881 0.000104 ***
factor(rank)4 -1.551464   0.417832  -3.713 0.000205 ***
```

.question[
If your friend re-took the GRE and increased their score by one standard deviation, what would be their new estimated *probability* of getting accepted?
]
]

---

### Activity

.large[
```
Coefficients:
               Estimate Std. Error z value Pr(>|z|)    
(Intercept)   -3.989979   1.139951  -3.500 0.000465 ***
gre            0.002264   0.001094   2.070 0.038465 *  
gpa            0.804038   0.331819   2.423 0.015388 *  
factor(rank)2 -0.675443   0.316490  -2.134 0.032829 *  
factor(rank)3 -1.340204   0.345306  -3.881 0.000104 ***
factor(rank)4 -1.551464   0.417832  -3.713 0.000205 ***
```

.question[
Calculate a 95% confidence interval for the change in *odds* of acceptance associated with a *one-unit* increase in GRE score, holding GPA and school rank fixed
]
]

---

### Activity

.large[
```
Coefficients:
               Estimate Std. Error z value Pr(>|z|)    
(Intercept)   -3.989979   1.139951  -3.500 0.000465 ***
gre            0.002264   0.001094   2.070 0.038465 *  
gpa            0.804038   0.331819   2.423 0.015388 *  
factor(rank)2 -0.675443   0.316490  -2.134 0.032829 *  
factor(rank)3 -1.340204   0.345306  -3.881 0.000104 ***
factor(rank)4 -1.551464   0.417832  -3.713 0.000205 ***
```

.question[
Now calculate a 95% confidence interval for the change in *odds* of acceptance associated with a one *standard deviation* increase in GRE score, holding GPA and school rank fixed
]
]

---

### Activity

.large[
95% confidence interval for change in *odds* of acceptance associated with a one *standard deviation* increase in GRE score, holding GPA and school rank fixed:

$$(1.014, 1.66)$$

Your friend is reluctant to retake the exam unless they believe that their odds of acceptance will increase by at least 25%.

.question[
Would you recommend that your friend re-takes the exam?
]
]




