---
title: "Activity"
format: pdf
editor: source
---

\vspace{-2.5cm}

**Group members:**

## Inference with Poisson regression

We are interested in analyzing the number of articles published by biochemistry PhD students. The data contains the following variables:

* `art`: articles published in last three years of Ph.D.
* `fem`: gender (recorded as men or women)
* `mar`: marital status (recorded as married or single)
* `kid5`: number of children under age six
* `phd`: prestige of Ph.D. program
* `ment`: articles published by their mentor in last three years

Your friend proposes the following Poisson regression model:

$$Articles_i \sim Poisson(\lambda_i)$$
\vspace{-0.5cm}
$$\log(\lambda_i) = \beta_0 + \beta_1 Female_i + \beta_2 Married_i + \beta_3 Kids_i + \beta_4 Prestige_i + \beta_5 Mentor_i$$
Here is the model output:

```
             Estimate Std. Error z value Pr(>|z|)    
(Intercept)  0.304617   0.102981   2.958   0.0031 ** 
femWomen    -0.224594   0.054613  -4.112 3.92e-05 ***
marMarried   0.155243   0.061374   2.529   0.0114 *  
kid5        -0.184883   0.040127  -4.607 4.08e-06 ***
phd          0.012823   0.026397   0.486   0.6271    
ment         0.025543   0.002006  12.733  < 2e-16 ***

    Null deviance: 1817.4  on 914  degrees of freedom
Residual deviance: 1634.4  on 909  degrees of freedom
```

\newpage

### Questions

1. We are interested in estimating the relationship between prestige and the number of articles published, after accounting for other factors. Create an appropriate confidence interval to address this question.

\vspace{3cm}

2. Do you think you need an offset in this model? If so, what would the offset be?





