---
title: "Activity"
format: pdf
editor: source
---

\vspace{-2.5cm}

**Group members:**

\vspace{-0.5cm}

# Mixed effects models

We have data on prices and other information for 1561 Airbnb rentals in Chicago, Illinois. Our goal is to model the relationship between price and overall satisfaction score. The information comes from 43 neighborhoods, and we have information on between 25 to 50 rentals per neighborhood. The variables we will be using are as follows:

* `price`: The price in US dollars of a one night rental
* `overallSatisfaction`: an average satisfaction score, given as numbers between 2.5 and 5
* `neighborhood`: the neighborhood in which the rental is located

The code and output below show the fitted mixed effects model:

```{r eval=F}
library(lme4)
m1 <- lmer(price ~ overall_satisfaction + (1 | neighborhood), data = bnb)
summary(m1)
```

```
Random effects:
 Groups       Name        Variance Std.Dev.
 neighborhood (Intercept) 1048     32.37   
 Residual                 6762     82.23   
Number of obs: 1561, groups:  neighborhood, 43

Fixed effects:
                     Estimate Std. Error t value
(Intercept)            27.275     30.547   0.893
overall_satisfaction   14.809      6.303   2.350
```

\newpage

1. Interpret the estimated fixed effect coefficients $\widehat{\beta}_0$ and $\widehat{\beta}_1$.

\vspace{3cm}

2. Calculate and interpret the estimated intra-class correlation.
