---
title: "Class activity"
format: html
---

**Instructions:** 

* Work individually or with a neighbor to answer the following questions 
* To get started, download the [class activity template](https://sta214-f25.github.io/class_activities/ca_34_template.qmd) file
* When you are finished, render the file as an HTML and submit the HTML to Canvas (let me know if you encounter any problems)

# Data

Anxiety can affect musicians before performances, and can negatively affect their ability to play and their emotional state. In a [2010 study](https://journals.sagepub.com/doi/10.1177/1948550610370492), researchers examined anxiety in 37 undergraduate music majors. For each musician, data was collected on anxiety levels before different performances (between 2 and 15 performances were measured for each musician). Each row in the data represents one performance; in this activity, we will work with the following variables:

* `id`: a unique identifier for the musician
* `na`: negative affect score (a measure of anxiety)
* `large`: whether the musician was performing as part of a large ensemble (large = 1), or as part of a small ensemble or solo (large = 0)
* `audience`: who attended (Instructor, Public, Students, or Juried)

The researchers hypothesize that audience type might impact performer anxiety, and that after accounting for audience type, students will be less anxious when performing in large ensembles. Furthermore, the researchers suspect that overall anxiety varies between individuals, *and* that the effect of ensemble size (large vs. small) is different for different individuals.



### Downloading the data

The following code imports the data and saves it as a data frame called `music`:

```r
music <- read_csv("https://sta214-f25.github.io/class_activities/music.csv")
```

# Questions

1. Write down a mixed effects model that matches the researchers' hypothesis.

2. Fit the mixed effects model in R, and report and interpret the estimated parameters.

3. Create a QQ plot for the residuals. Does it seem reasonable to assume normality here?
    * If you like `ggplot`, then `geom_qq` and `geom_qq_line` may be helpful
    * If you called your fitted model `m1`, then `residuals(m1)` will extract the residuals

4. Create a QQ plot for the random intercepts $\widehat{u}_i$. Does it seem reasonable to assume normality here?
    * If you called your fitted model `m1`, then `ranef(m1)$id[,1]` will extract the random intercepts

5. Create a QQ plot for the random slopes $\widehat{v}_i$. Does it seem reasonable to assume normality here?
    * If you called your fitted model `m1`, then `ranef(m1)$id[,2]` will extract the random slopes


```{r, include=F, eval=F}
music <- read_csv("https://sta214-f25.github.io/class_activities/music.csv")

m1 <- lmer(na ~ audience + large + (large|id), data = music)
```


